FROM eclipse-temurin:21-jre-jammy
LABEL maintainer="Michael Staehler"

VOLUME /tmp

ENV JAVA_OPTS="-Duser.timezone=Europe/Berlin"

EXPOSE 8080

COPY target/fredbet.jar fredbet.jar

CMD exec java $JAVA_OPTS -jar fredbet.jar
