ARG JRE_BASE_IMAGE=eclipse-temurin:21-jre-alpine

FROM ${JRE_BASE_IMAGE}

FROM eclipse-temurin:21-jre-jammy

LABEL maintainer="Michael Staehler"

WORKDIR /

ENV JAVA_TOOL_OPTIONS="-Duser.timezone=Europe/Berlin"

EXPOSE 8080

COPY target/fredbet.jar fredbet.jar

RUN useradd -m freddy
USER freddy

ENTRYPOINT ["java", "-jar", "fredbet.jar"]
CMD ["exec"]
