services:
  postgres:
    container_name: postgres
    image: postgres:18.4-alpine
    volumes:
      - postgres-only-vol:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fred
      - POSTGRES_PASSWORD=fred
      - POSTGRES_DB=fredbetdb
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fred -d fredbetdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  fredbet:
    profiles: ["app"] # run with 'docker compose --profile app build'
    container_name: fredbet
    build:
      dockerfile: Dockerfile-multistage
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/fredbetdb"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "fred"
      SPRING_DATASOURCE_PASSWORD: "fred"
volumes:
  postgres-only-vol:
