LIBYA=LY
FINLAND=FI
MALAYSIA=MY
ST_KITTS_AND_NEVIS=KN
ANGOLA=AO
JORDAN=JO
UNITED_ARAB_EMIRATES=AE
KOREA_DPR=KP
BARBADOS=BB
CAPE_VERDE_ISLANDS=CV
BAHAMAS=BS
GRENADA=GD
LIECHTENSTEIN=LI
NICARAGUA=NI
ENGLAND=gb-eng
RWANDA=RW
POLAND=PL
TRINIDAD_AND_TOBAGO=TT
US_VIRGIN_ISLANDS=VI
LUXEMBOURG=LU
QATAR=QA
GREECE=GR
SURINAME=SR
MALDIVES=MV
SLOVENIA=SI
HONDURAS=HN
IRELAND=IE
GABON=GA
GUINEA_BISSEAU=GW
CONGO=CD
TAJIKISTAN=TJ
DOMINICAN_REPUBLIC=DO
SOUTH_AFRICA=ZA
ISRAEL=IL
LATVIA=LV
AUSTRALIA=AU
ANTIGUA_AND_BARBUDA=AG
SOLOMON_ISLANDS=SB
BENIN=BJ
AFGHANISTAN=AF
CHAD=TD
NAMIBIA=NA
MONGOLIA=MN
SAO_TOME_E_PRINCIPE=ST
MOZAMBIQUE=MZ
SIERRA_LEONE=SL
ARMENIA=AM
MOLDOVA=MD
MALI=ML
ICELAND=IS
SWEDEN=SE
TURKS_AND_CAICOS_ISLANDS=TC
BELGIUM=BE
NETHERLANDS=NL
FRANCE=FR
CAMBODIA=KH
COLOMBIA=CO
CHINESE_TAIPEI=TW
COOK_ISLANDS=CK
CAYMAN_ISLANDS=KY
ERITREA=ER
NEW_CALEDONIA=NC
CHINA_PR=CN
GIBRALTAR=GI
MADAGASCAR=MG
SOUTH_SUDAN=SS
ZAMBIA=ZM
INDIA=IN
SYRIA=SY
NORWAY=NO
PAPUA_NEW_GUINEA=PG
SUDAN=SD
SCOTLAND=gb-sct
UGANDA=UG
IRAQ=IQ
UZBEKISTAN=UZ
LESOTHO=LS
NIGER=NE
BANGLADESH=BD
KYRGYZSTAN=KG
GEORGIA=GE
TONGA=TO
IRAN=IR
GHANA=GH
SEYCHELLES=SC
PARAGUAY=PY
URUGUAY=UY
NIGERIA=NG
TUNISIA=TN
BAHRAIN=BH
BELIZE=BZ
KENYA=KE
MAURITIUS=MU
EL_SALVADOR=SV
PANAMA=PA
CZECH_REPUBLIC=CZ
SLOVAKIA=SK
PHILIPPINES=PH
CONGO_DR=CD
USA=US
DENMARK=DK
NEPAL=NP
CUBA=CU
MYANMAR=MM
ECUADOR=EC
BRITISH_VIRGIN_ISLANDS=VG
CANADA=CA
BHUTAN=BT
PALESTINE=PS
MONTSERRAT=MS
GUATEMALA=GT
SINGAPORE=SG
CROATIA=HR
ALBANIA=AL
SPAIN=ES
JAMAICA=JM
CENTRAL_AFRICAN_REPUBLIC=CF
VIETNAM=VN
CAMEROON=CM
THAILAND=TH
SAMOA=WS
ESTONIA=EE
OMAN=OM
DJIBOUTI=DJ
SAN_MARINO=SM
ETHIOPIA=ET
BERMUDA=BM
GAMBIA=GM
AUSTRIA=AT
HAITI=HT
DOMINICA=DM
SOMALIA=SO
SENEGAL=SN
SAUDI_ARABIA=SA
AZERBAIJAN=AZ
ITALY=IT
YEMEN=YE
FIJI=FJ
PERU=PE
SRI_LANKA=LK
CURACAO=CW
MALTA=MT
BOTSWANA=BW
PUERTO_RICO=PR
TANZANIA=TZ
WALES=gb-wls
MAURITANIA=MR
LITHUANIA=LT
BRAZIL=BR
MACAU=MO
TOGO=TG
HUNGARY=HU
LEBANON=LB
EGYPT=EG
MOROCCO=MA
NORTH_IRELAND=gb-nir
SERBIA=RS
COMOROS=KM
BURKINA_FASO=BF
TURKEY=TR
SWITZERLAND=CH
EQUATORIAL_GUINEA=GQ
COSTA_RICA=CR
PAKISTAN=PK
CHILE=CL
ALGERIA=DZ
KAZAKHSTAN=KZ
ST_VINCENT_GRENADINES=VC
IVORY_COAST=CI
FAROE_ISLANDS=FO
CYPRUS=CY
SWAZILAND=SZ
ROMANIA=RO
TAHITI=PF
GUYANA=GY
GERMANY=DE
BURUNDI=BI
BULGARIA=BG
LAOS=LA
ARUBA=AW
MEXICO=MX
BRUNEI_DARUSSALAM=BN
ANDORRA=AD
ST_LUCIA=LC
GREAT_BRITAIN=GB
GUINEA=GN
GUAM=GU
MALAWI=MW
KOREA_REPUBLIC=KR
UKRAINE=UA
HONG_KONG=HK
ARGENTINA=AR
ANGUILLA=AI
BELARUS=BY
VENEZUELA=VE
TURKMENISTAN=TM
TIMOR_LESTE=TL
PORTUGAL=PT
BOSNIA_HERZEGOVINA=BA
BOLIVIA=BO
JAPAN=JP
RUSSIA=RU
MONTENEGRO=ME
KUWAIT=KW
MACEDONIA=MK
VANUATU=VU
NEW_ZEALAND=NZ
LIBERIA=LR
