LIBYA=LY
FINLAND=FI
MALAYSIA=MY
ST_KITTS_AND_NEVIS=KN
ANGOLA=AO
JORDAN=JO
UNITED_ARAB_EMIRATES=AE
KOREA_DPR=KP
BARBADOS=BB
CAPE_VERDE_ISLANDS=CV
CF_PACHUCA=null
BAHAMAS=BS
GRENADA=GD
LIECHTENSTEIN=LI
NICARAGUA=NI
ENGLAND=gb-eng
RWANDA=RW
POLAND=PL
TRINIDAD_AND_TOBAGO=TT
US_VIRGIN_ISLANDS=VI
LUXEMBOURG=LU
QATAR=QA
GREECE=GR
MANCHESTER_CITY=null
SURINAME=SR
MALDIVES=MV
SLOVENIA=SI
BOTAFOGO=null
HONDURAS=HN
IRELAND=IE
GABON=GA
GUINEA_BISSEAU=GW
CONGO=CD
TAJIKISTAN=TJ
DOMINICAN_REPUBLIC=DO
SOUTH_AFRICA=ZA
ISRAEL=IL
FC_SALZBURG=null
LATVIA=LV
AUSTRALIA=AU
ANTIGUA_AND_BARBUDA=AG
SOLOMON_ISLANDS=SB
BENIN=BJ
AFGHANISTAN=AF
CHAD=TD
NAMIBIA=NA
CF_MONTERREY=null
MONGOLIA=MN
SAO_TOME_E_PRINCIPE=ST
MOZAMBIQUE=MZ
SIERRA_LEONE=SL
ARMENIA=AM
MOLDOVA=MD
PALMEIRAS=null
MALI=ML
ICELAND=IS
SWEDEN=SE
TURKS_AND_CAICOS_ISLANDS=TC
BELGIUM=BE
NETHERLANDS=NL
FRANCE=FR
CAMBODIA=KH
COLOMBIA=CO
CHINESE_TAIPEI=TW
COOK_ISLANDS=CK
CLUB_LEON=null
CAYMAN_ISLANDS=KY
CA_RIVER_PLATE_MONTEVIDEO=null
ERITREA=ER
NEW_CALEDONIA=NC
CHINA_PR=CN
GIBRALTAR=GI
MADAGASCAR=MG
SOUTH_SUDAN=SS
ZAMBIA=ZM
INDIA=IN
SYRIA=SY
NORWAY=NO
MAMELODI_SUNDOWNS_FC=null
PAPUA_NEW_GUINEA=PG
SUDAN=SD
SCOTLAND=gb-sct
UGANDA=UG
IRAQ=IQ
UZBEKISTAN=UZ
WYDAD_CASABLANCA=null
LESOTHO=LS
NIGER=NE
URAWA_RED_DIAMONDS=null
BANGLADESH=BD
KYRGYZSTAN=KG
GEORGIA=GE
TONGA=TO
FC_INTERNAZIONALE_MILANO=null
IRAN=IR
BAYERN_MUENCHEN=null
GHANA=GH
SEYCHELLES=SC
PARAGUAY=PY
URUGUAY=UY
NIGERIA=NG
TUNISIA=TN
BAHRAIN=BH
BELIZE=BZ
KENYA=KE
PARIS_SAINT_GERMAIN=null
MAURITIUS=MU
EL_SALVADOR=SV
JUVENTUS_FC=null
PANAMA=PA
CZECH_REPUBLIC=CZ
SLOVAKIA=SK
PHILIPPINES=PH
CONGO_DR=CD
USA=US
DENMARK=DK
NEPAL=NP
CUBA=CU
MYANMAR=MM
ECUADOR=EC
BRITISH_VIRGIN_ISLANDS=VG
CANADA=CA
BHUTAN=BT
PALESTINE=PS
AUCKLAND_CITY=null
MONTSERRAT=MS
GUATEMALA=GT
SINGAPORE=SG
REAL_MADRID=null
CROATIA=HR
ALBANIA=AL
SPAIN=ES
CR_FLAMENGO=null
JAMAICA=JM
CENTRAL_AFRICAN_REPUBLIC=CF
VIETNAM=VN
CAMEROON=CM
THAILAND=TH
SAMOA=WS
ULSAN_HD=null
ESTONIA=EE
OMAN=OM
DJIBOUTI=DJ
SAN_MARINO=SM
ETHIOPIA=ET
BERMUDA=BM
GAMBIA=GM
AUSTRIA=AT
HAITI=HT
DOMINICA=DM
SOMALIA=SO
SENEGAL=SN
SAUDI_ARABIA=SA
CHELSEA_CREST=null
AZERBAIJAN=AZ
BORUSSIA_DORTMUND=null
ITALY=IT
YEMEN=YE
FIJI=FJ
PERU=PE
SRI_LANKA=LK
CURACAO=CW
MALTA=MT
BOTSWANA=BW
PUERTO_RICO=PR
TANZANIA=TZ
WALES=gb-wls
MAURITANIA=MR
LITHUANIA=LT
BRAZIL=BR
MACAU=MO
TOGO=TG
HUNGARY=HU
FC_PORTO=null
LEBANON=LB
EGYPT=EG
AL_AHLY=null
MOROCCO=MA
NORTH_IRELAND=gb-nir
SERBIA=RS
COMOROS=KM
BURKINA_FASO=BF
TURKEY=TR
SWITZERLAND=CH
EQUATORIAL_GUINEA=GQ
COSTA_RICA=CR
PAKISTAN=PK
FLUMINENSE_FC=null
CHILE=CL
ALGERIA=DZ
KAZAKHSTAN=KZ
ST_VINCENT_GRENADINES=VC
IVORY_COAST=CI
FAROE_ISLANDS=FO
CYPRUS=CY
SWAZILAND=SZ
ROMANIA=RO
TAHITI=PF
GUYANA=GY
BENFICA_LISSABON=null
GERMANY=DE
BURUNDI=BI
BULGARIA=BG
LAOS=LA
ARUBA=AW
MEXICO=MX
BRUNEI_DARUSSALAM=BN
ANDORRA=AD
ST_LUCIA=LC
GREAT_BRITAIN=GB
GUINEA=GN
GUAM=GU
MALAWI=MW
BOCA_JUNIORS=null
KOREA_REPUBLIC=KR
UKRAINE=UA
HONG_KONG=HK
ARGENTINA=AR
ANGUILLA=AI
BELARUS=BY
VENEZUELA=VE
TURKMENISTAN=TM
INTER_MIAMI=null
ATLETICO_MADRID=null
TIMOR_LESTE=TL
AL_HILAL=null
PORTUGAL=PT
BOSNIA_HERZEGOVINA=BA
BOLIVIA=BO
JAPAN=JP
ESPERANCE_SPORTIVE_TUNIS=null
RUSSIA=RU
MONTENEGRO=ME
KUWAIT=KW
SEATLE_SOUNDERS=null
MACEDONIA=MK
VANUATU=VU
NEW_ZEALAND=NZ
AL_AIN_FC=null
LIBERIA=LR
