version: "3"

services:
  mariadb:
    image: mariadb:12.0
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
     - MYSQL_DATABASE=fredbetdb
     - MYSQL_ROOT_PASSWORD=secred
     - MYSQL_USER=fred
     - MYSQL_PASSWORD=fred
volumes:
  database_data:
