services:
    mysqldb:
      image: mysql:8.0-debian
      ports:
        - "3306:3306"
      environment:
       - MYSQL_DATABASE=fredbetdb
       - MYSQL_ROOT_PASSWORD=secred
       - MYSQL_USER=fred
       - MYSQL_PASSWORD=fred
      volumes:
        - database_data:/var/lib/mysql
    fredbet:
      image: fred4jupiter/fredbet:latest
      links:
        - mysqldb
      depends_on:
        - mysqldb
      ports:
        - "8080:8080"
      environment:
       - SPRING_PROFILES_ACTIVE=prod
       - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/fredbetdb
       - SPRING_DATASOURCE_USERNAME=fred
       - SPRING_DATASOURCE_PASSWORD=fred
       - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
volumes:
  database_data:
