services:
  traefik:
    image: "traefik:v3.5"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8180:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  fredbet:
    image: "fred4jupiter/fredbet:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fredbet.rule=Host(`fredbet.localhost`)"
      - "traefik.http.routers.fredbet.entrypoints=web"
      - "traefik.http.services.fredbet.loadbalancer.server.port=8080"
