package de.fred4jupiter.fredbet.integration.model;

public enum FdMatchStage {

    FINAL, THIRD_PLACE, SEMI_FINALS, QUARTER_FINALS, LAST_16, LAST_32, LAST_64,
    ROUND_4, ROUND_3, ROUND_2, ROUND_1, GROUP_STAGE, PRELIMINARY_ROUND, QUALIFICATION,
    QUALIFICATION_ROUND_1, QUALIFICATION_ROUND_2, QUALIFICATION_ROUND_3, PLAYOFF_ROUND_1,
    PLAYOFF_ROUND_2, PLAYOFFS, REGULAR_SEASON, CLAUSURA, APERTURA, CHAMPIONSHIP,
    RELEGATION, RELEGATION_ROUND, LEAGUE_STAGE
}
