name: Java 25

on:
  push:
    branches:
      - 'java25'

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      maven_command: 'mvn -B verify'
      upload_artifact: false
      java_version: '25'
