name: Publish Manual Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The application release version'
        required: true
        default: '4.1.1'

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      maven_command: 'mvn -Drevision=${{ github.event.inputs.release_version }} -B verify'
      upload_artifact: true
  docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_IMAGE: fred4jupiter/fredbet
      DOCKER_TARGET_PLATFORM: linux/arm64/v8,linux/amd64
#    outputs:
#      release_version: ${{steps.version_update.outputs.release-version}} # use in jobs: ${{needs.build_tag_repo.outputs.release_version}}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Download jar file
        uses: actions/download-artifact@v4
        with:
          name: fredbet.jar
          run-id: ${{needs.build.outputs.jar_file_id}}
          path: target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker buildx build \
            --platform ${DOCKER_TARGET_PLATFORM} \
            --tag docker.io/${DOCKER_IMAGE}:${{ github.event.inputs.release_version }} \
            --tag ghcr.io/${DOCKER_IMAGE}:${{ github.event.inputs.release_version }} \
            --file ./Dockerfile-single \
            --output type=image,push=true .
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{github.event.inputs.release_version}}
          release_name: Release ${{github.event.inputs.release_version}}
          draft: false
          prerelease: false
          body: ${{steps.changelog.outputs.changelog}}
