name: Publish Docker latest image

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      maven_command: 'mvn -B verify'
      upload_artifact: true
  docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_IMAGE: fred4jupiter/fredbet
      DOCKER_TARGET_PLATFORM: linux/arm64/v8,linux/amd64
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Download jar file
        uses: actions/download-artifact@v4
        with:
          name: fredbet.jar
          run-id: ${{needs.build.outputs.jar_file_id}}
          path: target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker buildx build \
            --platform ${DOCKER_TARGET_PLATFORM} \
            --tag docker.io/${DOCKER_IMAGE}:latest \
            --tag ghcr.io/${DOCKER_IMAGE}:latest \
            --file ./Dockerfile-single \
            --output type=image,push=true .
