services:
  traefik:
    image: traefik:v3.7
    container_name: "traefik"
    restart: always
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL_ADDRESS}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8180:8080"
    volumes:
      - letsencrypt-vol:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  postgres:
    image: postgres:18.4-alpine
    container_name: "postgres"
    restart: always
    volumes:
      - postgres-vol:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - TZ=Europe/Berlin
    command:
      - "postgres"
      - "-c"
      - "lo_compat_privileges=on"
  databasus:
    image: databasus/databasus:v3.42.0
    depends_on:
      - postgres
    ports:
      - "4005:4005"
    volumes:
      - databasus-vol:/databasus-data
  fredbet:
    image: ghcr.io/fred4jupiter/fredbet:latest
    # image: fred4jupiter/fredbet:latest
    container_name: "fredbet"
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fredbet.rule=${DOMAIN_NAMES}"
      - "traefik.http.routers.fredbet.entrypoints=websecure"
      - "traefik.http.routers.fredbet.tls=true"
      - "traefik.http.routers.fredbet.tls.certresolver=letsencrypt"
      - "traefik.http.routers.fredbet.service=fredbet"
      - "traefik.http.services.fredbet.loadbalancer.server.port=8080"
      - "traefik.http.routers.fredbet.middlewares=fredbet-headers"
      - "traefik.http.middlewares.fredbet-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - FREDBET_INTEGRATION_FOOTBALL_DATA_API_TOKEN=${FOOTBALL_API_TOKEN}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  letsencrypt-vol:
  postgres-vol:
  databasus-vol:
